name: Continuous Integration

on:
  pull_request:
    branches: ["Dev"]

#permissions:
#  contents: read

jobs:
  test:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
